name: wantly
description: "내가 정말 원하는 것만 갖자 - 개인 소비 관리 앱"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI Framework
  cupertino_icons: ^1.0.8

  # 상태 관리
  provider: ^6.1.1

  # 로컬 데이터베이스
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  # 데이터 모델
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # 드래그앤드롭
  reorderables: ^0.6.0

  # 애니메이션
  animations: ^2.0.11
  lottie: ^3.0.0
  shimmer: ^3.0.0

  # 차트 & 그래프
  fl_chart: ^0.66.0

  # 이미지
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # UI 컴포넌트
  flutter_slidable: ^3.0.1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0

  # 날짜 & 국제화
  intl: ^0.19.0

  # 유틸리티
  uuid: ^4.3.3
  logger: ^2.0.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 코드 생성
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
